/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", '[data-theme="night"]'],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },

        /* NookUI 设计令牌（CSS 变量引用） */
        'nook-cream': 'var(--nook-cream)',
        'nook-paper': 'var(--nook-paper)',
        'nook-brown': 'var(--nook-brown)',
        'nook-wood': 'var(--nook-wood)',
        'nook-wood-light': 'var(--nook-wood-light)',
        'ac-green': { DEFAULT: 'var(--ac-green)', dark: 'var(--ac-green-dark)' },
        'ac-blue': { DEFAULT: 'var(--ac-blue)', dark: 'var(--ac-blue-dark)' },
        'ac-yellow': { DEFAULT: 'var(--ac-yellow)', dark: 'var(--ac-yellow-dark)' },
        'ac-coral': { DEFAULT: 'var(--ac-coral)', dark: 'var(--ac-coral-dark)' },
        'ac-sky': { DEFAULT: 'var(--ac-sky)', dark: 'var(--ac-sky-dark)' },
        'color-primary': 'var(--color-primary)',
        'color-primary-dark': 'var(--color-primary-dark)',
        'color-success': 'var(--color-success)',
        'color-success-dark': 'var(--color-success-dark)',
        'color-info': 'var(--color-info)',
        'color-info-dark': 'var(--color-info-dark)',
        'color-warning': 'var(--color-warning)',
        'color-warning-dark': 'var(--color-warning-dark)',
        'color-danger': 'var(--color-danger)',
        'color-danger-dark': 'var(--color-danger-dark)',
        'color-secondary': 'var(--color-secondary)',
        'color-secondary-dark': 'var(--color-secondary-dark)',
        'color-accent': 'var(--color-accent)',
        'color-accent-dark': 'var(--color-accent-dark)',
        'color-focus': 'var(--color-focus)',
        'bg-page': 'var(--bg-page)',
        'bg-surface': 'var(--bg-surface)',
        'bg-surface-alt': 'var(--bg-surface-alt)',
        'bg-elevated': 'var(--bg-elevated)',
        'text-heading': 'var(--text-heading)',
        'text-body': 'var(--text-body)',
        'text-caption': 'var(--text-caption)',
        'text-inverse': 'var(--text-inverse)',
        'text-on-bright': 'var(--text-on-bright)',
        'text-on-blue': 'var(--text-on-blue)',
        'text-on-yellow': 'var(--text-on-yellow)',
        'text-info': 'var(--text-info)',
        'text-danger': 'var(--text-danger)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-strong': 'var(--border-strong)',
        'border-light': 'var(--border-light)',
        'ac-sky-bright': 'var(--ac-sky-bright)',
        'ac-dodo': 'var(--ac-dodo)',
        'ac-nintendo': 'var(--ac-nintendo)',
        'ac-nook-mint': 'var(--ac-nook-mint)',
        'ac-sand': 'var(--ac-sand)',
        'ac-grass': 'var(--ac-grass)',
        'ac-leaf': 'var(--ac-leaf)',
        'ac-autumn': 'var(--ac-autumn)',
        'ac-starry': 'var(--ac-starry)',
        'ac-ocean': 'var(--ac-ocean)',
        'btn-ring-green': 'var(--btn-ring-green)',
        'btn-ring-blue': 'var(--btn-ring-blue)',
        'btn-ring-yellow': 'var(--btn-ring-yellow)',
        'btn-ring-coral': 'var(--btn-ring-coral)',

        /* 向后兼容（旧代码可能直接用了这些对象路径） */
        nook: {
          cream: 'var(--nook-cream)',
          paper: 'var(--nook-paper)',
          wood: 'var(--nook-wood)',
          brown: 'var(--nook-brown)',
        },
        ac: {
          green: 'var(--ac-green)',
          'green-dark': 'var(--ac-green-dark)',
          blue: 'var(--ac-blue)',
          'blue-dark': 'var(--ac-blue-dark)',
          pink: 'var(--ac-pink)',
          'pink-dark': 'var(--ac-pink-dark)',
          yellow: 'var(--ac-yellow)',
          'yellow-dark': 'var(--ac-yellow-dark)',
          coral: 'var(--ac-coral)',
          'coral-dark': 'var(--ac-coral-dark)',
          lavender: 'var(--ac-lavender)',
          'lavender-dark': 'var(--ac-lavender-dark)',
          mint: 'var(--ac-mint)',
          peach: 'var(--ac-peach)',
        },
      },

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'button': 'var(--radius-button)',
        'button-rect': 'var(--radius-button-rect)',
        'game': 'var(--radius-game)',
        'card': 'var(--radius-card)',
        'input': 'var(--radius-input)',
        'panel': 'var(--radius-panel)',
        'chip': 'var(--radius-chip)',
      },

      boxShadow: {
        'soft': 'var(--shadow-soft)',
        'colored': 'var(--shadow-colored)',
        'colored-blue': 'var(--shadow-colored-blue)',
        'colored-coral': 'var(--shadow-colored-coral)',
        'colored-yellow': 'var(--shadow-colored-yellow)',
        'card-hover': 'var(--shadow-card-hover)',
        'card-hover-blue': 'var(--shadow-card-hover-blue)',
        'card-hover-green': 'var(--shadow-card-hover-green)',
        'card-hover-coral': 'var(--shadow-card-hover-coral)',
        'card-hover-yellow': 'var(--shadow-card-hover-yellow)',
        'modal': 'var(--shadow-modal)',
        'switch-thumb': 'var(--shadow-switch-thumb)',
        'inset-toggle': 'var(--shadow-inset-toggle)',
        'inset-toggle-off': 'var(--shadow-inset-toggle-off)',
        '3d-btn': 'var(--shadow-3d-btn)',
        '3d-btn-hover': 'var(--shadow-3d-btn-hover)',
        '3d-btn-active': 'var(--shadow-3d-btn-active)',
        '3d-input': 'var(--shadow-3d-input)',
        'btn-green': 'var(--shadow-btn-green)',
        'btn-green-hover': 'var(--shadow-btn-green-hover)',
        'btn-blue': 'var(--shadow-btn-blue)',
        'btn-blue-hover': 'var(--shadow-btn-blue-hover)',
        'btn-coral': 'var(--shadow-btn-coral)',
        'btn-coral-hover': 'var(--shadow-btn-coral-hover)',
        'btn-yellow': 'var(--shadow-btn-yellow)',
        'btn-yellow-hover': 'var(--shadow-btn-yellow-hover)',
        'tag': 'var(--shadow-tag)',
        'tag-hover': 'var(--shadow-tag-hover)',
        'tabs-active': 'var(--shadow-tabs-active)',
        'steps-active': 'var(--shadow-steps-active)',
        'pagination-active': 'var(--shadow-pagination-active)',
        'toast': 'var(--shadow-toast)',
        'tooltip': 'var(--shadow-tooltip)',
        'toggle3d': 'var(--shadow-toggle3d)',
        'toggle3d-active': 'var(--shadow-toggle3d-active)',
      },

      fontFamily: {
        nook: ["WenYuanRounded", "PingFang SC", "Microsoft YaHei", "sans-serif"],
      },

      keyframes: {
        float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-8px)' } },
        wiggle: { '0%, 100%': { transform: 'rotate(0deg)' }, '25%': { transform: 'rotate(-3deg)' }, '75%': { transform: 'rotate(3deg)' } },
        popIn: { '0%': { opacity: '0', transform: 'scale(0.8) translateY(20px)' }, '100%': { opacity: '1', transform: 'scale(1) translateY(0)' } },
        bounceSoft: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } },
        shimmer: { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        leafSway: { '0%, 100%': { transform: 'rotate(-5deg)' }, '50%': { transform: 'rotate(5deg)' } },
        stripeFlow: { '0%': { backgroundPosition: '0 0' }, '100%': { backgroundPosition: '24px 0' } },
        splashBurst: { '0%': { transform: 'scale(0)', opacity: '0.6' }, '50%': { transform: 'scale(1.2)', opacity: '0.3' }, '100%': { transform: 'scale(2)', opacity: '0' } },
        'ripple-splash': { '0%': { transform: 'translate(-50%,-50%) scale(0)', opacity: '0.5' }, '100%': { transform: 'translate(-50%,-50%) scale(4)', opacity: '0' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'pulse-ring': { '0%': { transform: 'scale(0.8)', opacity: '0.5' }, '100%': { transform: 'scale(1.3)', opacity: '0' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(30px) scale(0.95)' }, '100%': { opacity: '1', transform: 'translateX(0) scale(1)' } },
        bubblePop: { '0%': { opacity: '0', transform: 'scale(0.5) translateY(20px)' }, '70%': { transform: 'scale(1.05) translateY(-4px)' }, '100%': { opacity: '1', transform: 'scale(1) translateY(0)' } },
        bubbleIdle: { '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' }, '25%': { borderRadius: '40% 60% 70% 30% / 50% 60% 30% 60%' }, '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' }, '75%': { borderRadius: '50% 40% 30% 60% / 60% 40% 60% 30%' } },
        leafWiggle: { '0%, 100%': { transform: 'rotate(-10deg)' }, '50%': { transform: 'rotate(10deg)' } },
        handWiggle: { '0%, 100%': { transform: 'rotate(-10deg) translateY(0)' }, '50%': { transform: 'rotate(10deg) translateY(-3px)' } },
        iconBounce: { '0%, 100%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.2)' } },
        blink: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0' } },
        spin: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
      },

      animation: {
        'float': 'float 4s ease-in-out infinite',
        'wiggle': 'wiggle 0.5s ease-in-out',
        'pop': 'popIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'bounce-soft': 'bounceSoft 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'leaf-sway': 'leafSway 2s ease-in-out infinite',
        'stripe-flow': 'stripeFlow 0.6s linear infinite',
        'splash-burst': 'splashBurst 0.6s ease-out forwards',
        'ripple-splash': 'ripple-splash 0.5s ease-out forwards',
        'slide-up': 'slideUp 0.4s ease-out forwards',
        'pulse-ring': 'pulse-ring 1.5s ease-out infinite',
        'slide-in-right': 'slideInRight 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'bubble-pop': 'bubblePop 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'blob-idle': 'bubbleIdle 4s ease-in-out infinite',
        'leaf-wiggle': 'leafWiggle 0.3s ease-in-out',
        'hand-wiggle': 'handWiggle 1.5s ease-in-out infinite',
        'icon-bounce': 'iconBounce 0.3s ease-in-out',
        'blink': 'blink 1s step-end infinite',
        'spin-fast': 'spin 0.8s linear infinite',
        'fade-in': 'fadeIn 0.3s ease-out forwards',
      },

      transitionTimingFunction: {
        'nook': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
